OPENAI_API_KEY = "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"

HUNTER_API_KEY = "de5f85ea89e610c41c84e113d58280630f1cbb8b"
